security:
    # Gestionnaire de mot de passe pour les utilisateurs
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Fournisseur d'utilisateurs basé sur l'entité User
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_home

    # Contrôle d'accès aux différentes routes
    access_control:
        # Pages publiques accessibles à tout le monde
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/css, roles: PUBLIC_ACCESS }
        - { path: ^/images, roles: PUBLIC_ACCESS }
        - { path: ^/js, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS } # Ajout d'une règle explicite pour la page d'accueil

        # Accès restreint aux pages admin (seulement pour les admins)
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Accès restreint aux pages de profil (pour les utilisateurs connectés)
        - { path: ^/profile, roles: ROLE_USER }
